project:
  type: website
  output-dir: docs

website:
  title: "Jason Xu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Viz
        menu:
        - text: Scent & Frangrance
          href: The Scent of Data.qmd
        - text: Childcare 
          href: Childcare Costs.qmd
        - text: Macbeth
          href: Strings.qmd
        - text: Simulations
          href: Simulation Analysis.qmd
        - text: Ethics in Data Science 
          href: Ethics.qmd
        - text: SQL
          href: SQL.qmd

format:
  html:
    theme: 
      light: lumen
      dark: superhero
    css: styles.css
    toc: true

editor: visual

