project:
  type: website
  output-dir: docs

website:
  title: "Jason Xu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Viz
        menu:
        - text: Scent & Frangrance
          href: The Scent of Data.qmd
        - text: viz 2
          # href:
        
format:
  html:
    theme: 
      light: lumen
      dark: superhero
    css: styles.css
    toc: true

editor: visual

