project:
  type: website
  output-dir: docs

website:
  title: "Jason Xu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Jason CV.pdf
        text: My CV
        target: _blank
      - text: Projects
        menu:
        - text: Shiny
          href: The Scent of Data.qmd
        - text: Scatter Plot
          href: Childcare Costs.qmd
        - text: Regular Expression
          href: Strings.qmd
        - text: Simulation
          href: Simulation Analysis.qmd
        - text: Ethics in Data Science 
          href: Ethics.qmd
        - text: SQL
          href: SQL.qmd
      - text: How a project is done
        href: DS002 Final Prez.qmd
        target: _blank

format:
  html:
    theme: 
      light: lumen
      dark: superhero
    css: styles.css
    toc: true

editor: visual

